version: "3.9"
services:
  backend:
    build: 
      context: ./backend
    image: node
    volumes:
      - ./backend:/home/backend
    working_dir: /home/backend
    expose: 
      - "3000"
    ports: 
      - 9229:9229
    entrypoint: npm run start:debug
  frontend:
    build: 
      context: ./frontend
    image: node
    volumes: 
      - ./frontend:/home/frontend
    working_dir: /home/frontend
    expose: 
      - "3000"
    entrypoint: npm run dev
  nginx:
    build: ./nginx
    ports: 
      - 80:80
  db:
    image: postgres
    restart: always
    expose: 
    - "5432"
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081"
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports: 
  #     - 9411:9411
  #   environment: 
  #     STORAGE_TYPE: elasticsearch
  #     ES_HOSTS: http://elasticsearch:9200
  #     # CASSANDRA_CONTACT_POINTS: cassandra:9042
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  # cassandra:
  #   container_name: backstage_cassandra
  #   image: cassandra
  #   expose: 
  #     - "9042"
  #   environment: 
  #     JVM_OPTS: "-Xms250M -Xmx250M"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 400M
  elasticsearch:
    image: elasticsearch:7.10.1
    expose: 
      - "9200"
      - "9300"
    ports: 
      - 9200:9200
    environment: 
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms250m -Xmx250m"
    deploy:
      resources:
        limits:
          memory: 400M
  kibana: 
    image: kibana:7.10.1
    ports: 
      - 5601:5601
  jaeger:
    image: jaegertracing/all-in-one
    ports: 
      - 16686:16686
    expose: 
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "14268"
      - "14250"
      # - "9411"
    deploy:
      resources:
        limits:
          memory: 250M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    # environment: 
      # COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
